# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.id)


#Department.create([{ name: 'Lima' }])
#department = Department.find_by_name('Lima')
#Province.create(name: 'Lima', department_id: department.id)

#ActiveRecord::Base.connection.execute("ALTER TABLE distriicts AUTO_INCREMENT = 1  )

District.create([{ name: 'Ate' }])
District.create([{ name: 'Breña' }])
District.create([{ name: 'Carabayllo' }])
District.create([{ name: 'Comas' }])
District.create([{ name: 'Chaclacayo' }])
District.create([{ name: 'Chorrillos' }])
District.create([{ name: 'La Victoria' }])
District.create([{ name: 'La Molina' }])
District.create([{ name: 'Lima' }])
District.create([{ name: 'Lince' }])
District.create([{ name: 'Lurigancho' }])
District.create([{ name: 'Lurin' }])
District.create([{ name: 'Magdalena del mar' }])
District.create([{ name: 'Miraflores' }])
District.create([{ name: 'Pachacamac' }])
District.create([{ name: 'Pueblo Libre' }])
District.create([{ name: 'Pucusana' }])
District.create([{ name: 'Puente Piedra' }])
District.create([{ name: 'Punta Hermosa' }])
District.create([{ name: 'Punta Negra' }])
District.create([{ name: 'Rimac' }])
District.create([{ name: 'San Bartolo' }])
District.create([{ name: 'San Isidro' }])
District.create([{ name: 'Barranco' }])
District.create([{ name: 'San Martin de Porres' }])
District.create([{ name: 'San Miguel' }])
District.create([{ name: 'Santa Maria del Mar' }])
District.create([{ name: 'Santa Rosa' }])
District.create([{ name: 'Santiago de Surco' }])
District.create([{ name: 'Surquillo' }])
District.create([{ name: 'Villa Maria del Triunfo' }])
District.create([{ name: 'Jesus Maria' }])
District.create([{ name: 'Independencia' }])
District.create([{ name: 'El Agustino' }])
District.create([{ name: 'San Juan de Miraflores' }])
District.create([{ name: 'San Juan de Lurigancho' }])
District.create([{ name: 'San Luis' }])
District.create([{ name: 'Cieneguilla' }])
District.create([{ name: 'San Borja' }])
District.create([{ name: 'Villa el Salvador' }])
District.create([{ name: 'Los Olivos' }])
District.create([{ name: 'Santa Anita' }])

